refactor set_module_by_name
huggingface/quanto pull request #153
Opened 2024-04-05 15:41 UTC by hayun0909

In the `set_module_by_name` function, the process of returning `next_module` using a loop is replaced with `get_submodule`.

2024-04-06 10:02 UTC, dacorvo requested changes
Thanks for the pull-request: less code is good !
Please amend your commit message to follow the conventional commits convention and force-push your branch.
`refactor: use get_submodule in set_module_by_name`

2024-04-12 15:42 UTC, hayun0909 commented
Thank you for the helpful guide! 
I amended the commit as you suggested.

2024-04-12 16:55 UTC, dacorvo commented
Please do:

```
$ make style
```
 and amend your commit once the style has been fixed

2024-04-16 03:35 UTC, hayun0909 commented
I've completed what you mentioned. Thank you for the detailed explanation.

2024-04-16 07:23 UTC, dacorvo approved these changes
Thank you for the pull-request.

2024-04-16 07:23 UTC, merged